/*
 * Living Draft — Customizer live preview.
 *
 * Runs INSIDE the Customizer preview iframe (never on public pages).
 * Subscribes to each token whose transport is 'postMessage' and updates
 * a CSS custom property on :root every time the corresponding control
 * changes, so users see the change instantly as they drag/pick.
 *
 * The token→selector→property map is passed in via wp_localize_script
 * as `livingdraftPreview.tokens`, generated by register.php.
 *
 * === HOW A TOKEN GETS WIRED UP ===
 *
 * For each entry in livingdraftPreview.tokens:
 *   1. wp.customize( token_id, callback ) subscribes to changes.
 *   2. Callback receives the new value.
 *   3. If token has a 'lookup' table (fonts), look the value up in it.
 *   4. If token has a 'wrapper' (e.g. '%dpx'), format the value.
 *   5. Apply the resulting string to the target selector's CSS property.
 *
 * === WHAT LIVE PREVIEW CAN'T DO ===
 *
 * Structural changes (sidebar on/off, changing HTML markup) require a
 * full refresh — those tokens declare transport: 'refresh' in the
 * registry, so they don't show up in livingdraftPreview.tokens at all.
 */

( function ( wp, $ ) {
	'use strict';

	if ( ! wp || ! wp.customize || ! window.livingdraftPreview ) {
		return;
	}

	var tokens = window.livingdraftPreview.tokens || {};

	// Wire up each token.
	Object.keys( tokens ).forEach( function ( tokenId ) {
		var entry = tokens[ tokenId ];

		wp.customize( tokenId, function ( setting ) {
			setting.bind( function ( newValue ) {
				applyChange( newValue, entry );
			} );
		} );
	} );

	/**
	 * Push a new value into the preview by mutating a CSS custom property.
	 *
	 * @param {*}      value  New value from the Customizer control.
	 * @param {Object} entry  { selector, property, wrapper?, lookup? }
	 */
	function applyChange( value, entry ) {
		if ( ! entry || ! entry.property ) {
			return;
		}

		var resolved = value;

		// Lookup transformation (e.g. font key → font stack).
		if ( entry.lookup && entry.lookup[ value ] && entry.lookup[ value ].stack ) {
			resolved = entry.lookup[ value ].stack;
		}

		// Wrapper transformation (e.g. add 'px' or 'ch' suffix).
		if ( entry.wrapper ) {
			resolved = entry.wrapper.replace( /%[sd]/, resolved );
		}

		// Empty means "revert to default" — remove the inline property.
		var target = document.querySelector( entry.selector || ':root' );
		if ( ! target ) {
			return;
		}

		if ( '' === resolved || null === resolved || undefined === resolved ) {
			target.style.removeProperty( entry.property );
		} else {
			target.style.setProperty( entry.property, resolved );
		}
	}

} )( window.wp, window.jQuery );
